server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/ms-mail
spring.datasource.username=postgres
spring.datasource.password=231506

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.addresses=amqps://qagthnns:DAxJ-BcnK2EpR6JDYWkaUyk-LQ7IWdE0@fuji.lmq.cloudamqp.com/qagthnns

broker.queue.email.name=default.email

spring.mail.host=smtp.gamil.com
spring.mail.port=587
spring.mail.username=decod***@gmail.com
spring.mail.password=**** **** **** ****
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true